---
# Source: concourse/templates/web-role.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: concourse-web
  labels:
    app: concourse-web
    chart: concourse-3.7.2
    heritage: Tiller
    release: concourse
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]