---
# Source: concourse/templates/web-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: concourse-web
  labels:
    app: concourse-web
    chart: concourse-3.7.2
    heritage: Tiller
    release: concourse