---
# Source: concourse/templates/web-deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: concourse-web
  labels:
    app: concourse-web
    chart: "concourse-3.7.2"
    release: "concourse"
    heritage: "Tiller"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: concourse-web
        release: "concourse"
      annotations:
        {}
        
    spec:
      serviceAccountName: concourse-web
      tolerations:
        []
        
      containers:
        - name: concourse-web
          image: "concourse/concourse:4.2.2"
          imagePullPolicy: "IfNotPresent"
          args:
            - "web"
          env:
            - name: CONCOURSE_BIND_PORT
              value: "8080"
            - name: CONCOURSE_ADD_LOCAL_USER
              valueFrom:
                secretKeyRef:
                  name: concourse-concourse
                  key: local-users
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CONCOURSE_PEER_URL
              value: "http://$(POD_IP):$(CONCOURSE_BIND_PORT)"
            - name: CONCOURSE_POSTGRES_HOST
              value: concourse-postgresql
            - name: CONCOURSE_POSTGRES_USER
              value: "concourse"
            - name: CONCOURSE_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: concourse-postgresql
                  key: postgres-password
            - name: CONCOURSE_POSTGRES_DATABASE
              value: "concourse"
            - name: CONCOURSE_KUBERNETES_IN_CLUSTER
              value: "true"
            - name: CONCOURSE_KUBERNETES_NAMESPACE_PREFIX
              value: concourse-
            - name: CONCOURSE_SESSION_SIGNING_KEY
              value: "/concourse-keys/session_signing_key"
            - name: CONCOURSE_MAIN_TEAM_LOCAL_USER
              value: "test"
            - name: CONCOURSE_TSA_BIND_PORT
              value: "2222"
            - name: CONCOURSE_TSA_HOST_KEY
              value: "/concourse-keys/host_key"
            - name: CONCOURSE_TSA_AUTHORIZED_KEYS
              value: "/concourse-keys/worker_key.pub"
          ports:
            - name: atc
              containerPort: 8080
            - name: tsa
              containerPort: 2222
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /api/v1/info
              port: atc
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 3
            
          readinessProbe:
            httpGet:
              path: /api/v1/info
              port: atc
            
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            
          volumeMounts:
            - name: concourse-keys
              mountPath: "/concourse-keys"
              readOnly: true
            - name: auth-keys
              mountPath: "/concourse-auth"
              readOnly: true
      affinity:
      volumes:
        - name: concourse-keys
          secret:
            secretName: concourse-concourse
            defaultMode: 0400
            items:
              - key: host-key
                path: host_key
              - key: session-signing-key
                path: session_signing_key
              - key: worker-key-pub
                path: worker_key.pub
        - name: auth-keys
          secret:
            secretName: concourse-concourse
            defaultMode: 0400
            items:
