---
# Source: concourse/templates/worker-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: concourse-worker
  labels:
    app: concourse-worker
    chart: concourse-3.7.2
    heritage: Tiller
    release: concourse