---
# Source: jenkins/templates/secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: jenkins
  labels:
    app: jenkins
    chart: "jenkins-0.20.1"
    release: "jenkins"
    heritage: "Tiller"
type: Opaque
data:
  
  jenkins-admin-password: "c2VjcmV0"
  
  jenkins-admin-user: "YWRtaW4="