---
# Source: concourse/charts/postgresql/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: concourse-postgresql
  labels:
    app: postgresql
    chart: postgresql-0.13.1
    release: concourse
    heritage: Tiller
data: