---
# Source: jaeger/templates/agent-ds.yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: jaeger-agent
  labels:
    app: jaeger
    jaeger-infra: agent-daemonset
    chart: jaeger-0.7.0
    component: agent
    heritage: Tiller
    release: jaeger
spec:
  template:
    metadata:
      labels:
        app: jaeger
        component: agent
        release: jaeger
        jaeger-infra: agent-instance
    spec:
      dnsPolicy: ClusterFirst
      nodeSelector:
        {}
        
      containers:
      - name: jaeger-agent
        image: jaegertracing/jaeger-agent:1.4.1
        imagePullPolicy: IfNotPresent
        env:
        - name: COLLECTOR_HOST_PORT
          valueFrom:
            configMapKeyRef:
              name: jaeger
              key: collector.host-port
        ports:
        - containerPort: 5775
          protocol: UDP
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
        - containerPort: 5778
          protocol: TCP
        resources:
          {}
          