---
# Source: jaeger/templates/cassandra-schema-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: jaeger-cassandra-schema
  labels:
    app: jaeger
    jaeger-infra: cassandra-schema-job
    chart: jaeger-0.7.0
    component: cassandra-schema
    heritage: Tiller
    release: jaeger
spec:
  activeDeadlineSeconds: 120
  template:
    metadata:
      name: jaeger-cassandra-schema
    spec:
      containers:
      - name: jaeger-cassandra-schema
        image: jaegertracing/jaeger-cassandra-schema:1.4.1
        imagePullPolicy: IfNotPresent
        env:
        - name: CQLSH_HOST
          valueFrom:
            configMapKeyRef:
              name: jaeger
              key: cassandra.servers
        - name: MODE
          valueFrom:
            configMapKeyRef:
              name: jaeger
              key: cassandra.schema.mode
        - name: DATACENTER
          valueFrom:
            configMapKeyRef:
              name: jaeger
              key: cassandra.datacenter.name
        - name: CASSANDRA_PORT
          valueFrom:
            configMapKeyRef:
              name: jaeger
              key: cassandra.port
        resources:
          {}
          
      restartPolicy: OnFailure