---
# Source: jaeger/templates/collector-deploy.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jaeger-collector
  labels:
    app: jaeger
    jaeger-infra: collector-deployment
    chart: jaeger-0.7.0
    component: collector
    heritage: Tiller
    release: jaeger
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jaeger
        component: collector
        release: jaeger
        jaeger-infra: collector-pod
    spec:
      nodeSelector:
        {}
        
      containers:
      - name: jaeger-collector
        image: jaegertracing/jaeger-collector:1.4.1
        imagePullPolicy: IfNotPresent
        env:
          - name: SPAN_STORAGE_TYPE
            valueFrom:
              configMapKeyRef:
                name: jaeger
                key: span-storage.type
          - name: CASSANDRA_SERVERS
            valueFrom:
              configMapKeyRef:
                name: jaeger
                key: cassandra.servers
          - name: CASSANDRA_PORT
            valueFrom:
              configMapKeyRef:
                name: jaeger
                key: cassandra.port
          - name: CASSANDRA_KEYSPACE
            valueFrom:
              configMapKeyRef:
                name: jaeger
                key: cassandra.keyspace
          - name: COLLECTOR_PORT
            valueFrom:
              configMapKeyRef:
                name: jaeger
                key: collector.port
          - name: COLLECTOR_HTTP_PORT
            valueFrom:
              configMapKeyRef:
                name: jaeger
                key: collector.http-port
          - name: COLLECTOR_ZIPKIN_HTTP_PORT
            valueFrom:
              configMapKeyRef:
                name: jaeger
                key: collector.zipkin.http-port
        ports:
        - containerPort: 14267
          name: tchannel
          protocol: TCP
        - containerPort: 14268
          name: http
          protocol: TCP
        - containerPort: 14269
          name: healthcheck
          protocol: TCP
        - containerPort: 9411
          name: zipkin
          protocol: TCP
        readinessProbe:
          httpGet:
            port: healthcheck
          initialDelaySeconds: 10
        livenessProbe:
          httpGet:
            port: healthcheck
          initialDelaySeconds: 10
        resources:
          {}
          
      dnsPolicy: ClusterFirst
      restartPolicy: Always