---
# Source: jaeger/templates/query-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  labels:
    app: jaeger
    jaeger-infra: query-service
    chart: jaeger-0.7.0
    component: query
    heritage: Tiller
    release: jaeger
spec:
  ports:
  - name: jaeger-query
    port: 80
    protocol: TCP
    targetPort: 16686
  selector:
    app: jaeger
    component: query
    release: jaeger
    jaeger-infra: query-pod
  type: ClusterIP